add hotel loader
happy-travel/juniper-connector pull request #30
Opened 2022-05-31 13:10 UTC by ayrat-molotkov

2022-06-17 10:56 UTC, DFSko approved these changes

2022-06-17 10:59 UTC, oleg-n-k approved these changes

2022-06-20 08:36 UTC, suhan3z commented on HappyTravel.JuniperConnector.Common/Infrastructure/JuniperServiceExtensions.cs
> +    public static T SetDefaultProperty<T>(this T request, JP_Login login)
А зачем для выставления констант использовать рефлексию?

2022-06-20 08:40 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +            await _updateHistoryService.SetError(updateId, ex);
Не в тему текущего реквеста, а почему с логирование зон хистори сервси не используется?

2022-06-20 08:43 UTC, suhan3z commented on HappyTravel.JuniperConnector.Common/Infrastructure/JuniperServiceExtensions.cs
>      private const long MaxReceivedMessageSize = 20000000;
Лучше доуказать размерность в названии байты это или что там, и почему именно такие лимиты?

2022-06-20 11:22 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Common/Infrastructure/JuniperServiceExtensions.cs
> +    public static T SetDefaultProperty<T>(this T request, JP_Login login)
Типы запросов везде разные, но у всех есть общее свойство типа JP_Login. Рефлексия используется для установки его значения. Типы запросов сгенерированы автоматически, поэтому наследование не используется.

2022-06-20 12:01 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +            await _hotelsUpdater.DeactivateAllHotels(cancellationToken);
Те, которые будут загружены до возникновения исключения, включатся. Остальные останутся выключены до следующего запуска апдейтера.

2022-06-21 07:22 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +            await _hotelsUpdater.DeactivateAllHotels(cancellationToken);
В общем логику над переделать, загружать пачками и если загрузка успешна тогда уже обновлять

2022-06-21 07:23 UTC, suhan3z requested changes
Логику загрузки над поменять, а то возможна ситуация при которой апдейтер всё выключит и ничего не загрузит

2022-06-22 07:27 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +            await _updateHistoryService.SetError(updateId, ex);
Хистори сервис нужен для того, чтобы обновлять данные по дате. В HotelsUpdater он, получается, тоже не нужен. Уберу.

2022-06-23 06:07 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Common/Infrastructure/JuniperServiceExtensions.cs
>      private const long MaxReceivedMessageSize = 20000000;
Не знаю, почему такие лимиты, но с ними работает. Пробовал выставлять максимально допустимые типами значения - появляются ошибки.

2022-06-29 17:12 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        await _hotelUpdater.DeactivateAllHotels(cancellationToken);
Так логика то не поменялась, сначала опять всё выключается, а потом если повезёт включится, надо не выключать

2022-06-29 17:21 UTC, suhan3z requested changes
Над поменять логику и выключать только те отели которые не пришли после всех реквестов

2022-06-30 05:32 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        await _hotelUpdater.DeactivateAllHotels(cancellationToken);
Логика отчасти поменялась: теперь отели грузятся пачками и, если одна пачка упадёт, то остальные продолжат грузиться и активироваться. Деактивация всех отелей полезна на тот случай, если у отеля что-то поменялось, но запрос с ним упал, а данные у отеля поменялись. В таком случае, вероятно, лучше, чтобы отель был деактивирован, а не показывал ложную информацию.
Как узнать, какие отели не пришли после всех запросов? Думается мне, что в любом случае эта операция создаст дополнительную нагрузку на сервер. Стоит ли оно того?

2022-06-30 05:53 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        await _hotelUpdater.DeactivateAllHotels(cancellationToken);
Как работает HotelLoader: 
сначала выполняются запросы GetHotelPortfolio, в которых постранично возвращаются id отелей (грубо говоря). Для выполнения каждого последующего запроса нужен токен следующей страницы, полученный в ответе на предыдущий запрос. Т.е., если запрос упадёт, то HotelLoader по сути остановил работу, т.к. нет токена следующей страницы. Оставшиеся в БД отели должны быть деактивированы. И нет разницы, когда их деактивировать: до или после.
Далее (а, вернее во время получения GetHotelPortfolio) с id-ми отелей, полученных с каждой страницы выполняются запросы на получение контента по этим отелям. Вот тут происходит загрузка пачками и активация отелей. И, в случае падения загрузки одной пачки, друге продолжат грузиться. Тут всё нормально и вы правы на счёт падения в одном из запросов.
Т.е., мне кажется, что нет смысла что-то менять.

2022-07-01 13:53 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        await _hotelUpdater.DeactivateAllHotels(cancellationToken);
Ну тут надо различать ошибки тогда сетевые на которые делаем ретраи и когда ответ вернули но с неправильным токеном или вообще без него

2022-07-04 09:39 UTC, suhan3z commented on HappyTravel.JuniperConnector.Common/JuniperService/JuniperServiceClient.cs
> +                SendTimeout = TimeSpan.FromMinutes(5)
А это чего не вынесли в константы?

2022-07-04 11:53 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        var affectedRowsCount = await _hotelUpdater.DeactivateNotFetched(modified, cancellationToken);
Давайте так если были ошибки любые, то ничего не деактивируем

2022-07-04 12:01 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        var affectedRowsCount = await _hotelUpdater.DeactivateNotFetched(modified, cancellationToken);
А если возникнет такая ситуация:
В одном из запросов возникла ошибка, следовательно мы не смогли завершить всю загрузку до конца. При этом, какие-то отели перестали приходить от поставщика. И мы из-за ошибки об этом не узнали. То у нас отель останется активным. Думаете, это правильно?

2022-07-04 12:05 UTC, evm-andrey commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        var affectedRowsCount = await _hotelUpdater.DeactivateNotFetched(modified, cancellationToken);
на текущей итерации это правильно

2022-07-04 12:07 UTC, suhan3z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        var affectedRowsCount = await _hotelUpdater.DeactivateNotFetched(modified, cancellationToken);
Да, по логике если мы выключим то что работает, опаснее чем если не выключим то что не работает, оно всё равно по факту уточнится на попытке букинга

2022-07-04 12:08 UTC, PKorovinPromo-Z commented on HappyTravel.JuniperConnector.Updater/Workers/HotelLoader.cs
> +        var affectedRowsCount = await _hotelUpdater.DeactivateNotFetched(modified, cancellationToken);
Т.е. у нас отель будет активным, а у поставщика его уже нет?

2022-07-04 13:59 UTC, suhan3z approved these changes

2022-07-04 14:01 UTC, merged